language: node_js
sudo: true
node_js:
  - 8
services:
  - mongodb
cache:
  directories:
    - "$HOME/.npm"
env:
  global:
    - CODECOV_TOKEN="83a5fba3-2c96-4f4a-af53-7526b41003de"
before_install:
  - npm config set loglevel warn
install:
  - npm install
  - npm install --prefix client
  - npm install codecov
  - npm install codecov --prefix client
before_script:
  - sleep 5
jobs:
  include:
    - stage: Unit and Integration tests
      script:
        - npm test
        - npm test --prefix client
