language: node_js
sudo: true
node_js:
  - "node"
services:
  - mongodb
cache:
  directories:
    - "$HOME/.npm"
before_install:
  - npm config set loglevel warn
install:
  - npm ci
  - npm install codecov
before_script:
  - sleep 5
jobs:
  include:
    - stage: Unit and Integration tests
      script:
        - npm test
        - npm test --prefix client
    - stage: Deployment
      script:
        - npm install --prefix client && npm run build --prefix client
